FLAGS = -Wall -lm

main: lab1.c padre.o hijo.o
	gcc $(FLAGS) -o main lab1.c padre.o hijo.o

padre.o: parte1.c
	gcc -c $(FLAGS) padre.c

hijo.o: parte2.c
	gcc -c $(FLAGS) hijo.c

clear:
	rm -f *.o main
